name: UltimateArena
main: net.dmulloy2.ultimatearena.UltimateArena
version: ${project.version} (Build ${project.build.number})
author: dmulloy2
softdepend: [WorldEdit, Vault, Essentials, Multiverse-Core, MyWorlds, ProtocolLib]
description: The Ultimate in Minecraft death sports and spleef!
load: postworld
commands:
  ua:
    description: UltimateArena base command
    usage: /<command> <args>
    aliases: [ultimatearena]

permissions:
  ultimatearena.admin:
    description: Allows access to all UltimateArena features
    default: false
    children:
      ultimatearena.builder: true
      ultimatearena.disable: true
      ultimatearena.enable: true
      ultimatearena.join.force: true
      ultimatearena.join.full: true
      ultimatearena.kick: true
      ultimatearena.option: true
      ultimatearena.pause: true
      ultimatearena.reload: true
      ultimatearena.start: true
      ultimatearena.stop: true
      ultimatearena.bypass: true
  ultimatearena.builder:
    description: Allows access to features meant for arena builders
    default: false
    children:
      ultimatearena.abandon: true
      ultimatearena.create: true
      ultimatearena.delete: true
      ultimatearena.setpoint: true
      ultimatearena.teleport: true
      ultimatearena.undo: true
      ultimatearena.build: true
  ultimatearena.abandon:
    description: Allows the abandoning of arenas
    default: false
  ultimatearena.class:
    description: Allows the switching of classes ingame
    default: true
  ultimatearena.classlist:
    description: Allows the listing of classes
    default: true
  ultimatearena.create:
    description: Allows the creation of arenas
    default: false
  ultimatearena.delete:
    description: Allows the deletion of arenas
    default: false
  ultimatearena.disable:
    description: Allows the disabling of arenas
    default: false
  ultimatearena.dislike:
    description: Allows the disliking of arenas
    default: true
  ultimatearena.enable:
    description: Allows the enabling of arenas
    default: false
  ultimatearena.info:
    description: Allows the viewing of arena info
    default: true
  ultimatearena.join:
    description: Allows the joining of arenas
    default: true
  ultimatearena.join.force:
    description: Allows the forcing of players into arenas
    default: false
  ultimatearena.join.full:
    description: Allows the joining of full arenas
    default: false
  ultimatearena.kick:
    description: Allows the kicking of players from arenas
    default: false
  ultimatearena.like:
    description: Allows the liking of arenas
    default: true
  ultimatearena.list:
    description: Allows the listing of available arenas
    default: true
  ultimatearena.option:
    description: Allows the usage of /ua option
    default: false
  ultimatearena.pause:
    description: Allows the pausing of arena start timers
    default: false
  ultimatearena.reload:
    description: Allows the reloading of the UltimateArena plugin
    default: false
  ultimatearena.setpoint:
    description: Allows the usage of /ua setpoint
    default: false
  ultimatearena.spectate:
    description: Allows the usage of /ua spectate
    default: true
  ultimatearena.start:
    description: Allows the force starting of arenas
    default: false
  ultimatearena.stats:
    description: Allows the viewing of arena stats
    default: true
  ultimatearena.stop:
    description: Allows the usage of /ua stop
    default: false
  ultimatearena.teleport:
    description: Allows the usage of /ua tp
    default: false
  ultimatearena.undo:
    description: Allows the usage of /ua undo
    default: false
  ultimatearena.version:
    description: Allows usage of /ua version
    default: true
  ultimatearena.build:
    description: Allows the breaking and placing of blocks in arenas
    default: false
  ultimatearena.bypass:
    description: Allows a player to bypass whitelisted commands
    default: false