name: UltimateArena
main: com.orange451.UltimateArena.UltimateArena
version: "2.4.2"
authors: [dmulloy2, orange451]
softdepend: [PVPGunPlus, Vault, Essentials]
description: The Ultimate in Minecraft death sports and spleef!
commands:
  ua:
    description: Ultimate Arena base command
    usage: /<command> <args>
    aliases: [ultimatearena]

permissions:
  ultimatearena.admin:
    description: Allows access to all UltimateArena features
    default: false
    children:
      ultimatearena.builder: true
      ultimatearena.forcestop: true
      ultimatearena.reload: true
      ultimatearena.disable: true
      ultimatearena.enable: true
      ultimatearena.kick: true
      ultimatearena.start: true
      ultimatearena.pause: true
  ultimatearena.builder:
    description: Allows access to features meant for builders
    default: false
    children:
      ultimatearena.create: true
      ultimatearena.setpoint: true
      ultimatearena.setdone: true
      ultimatearena.delete: true
      ultimatearena.stop: true
      ultimatearena.build: true
  ultimatearena.create:
    description: Allows the creation of arenas
    default: false
  ultimatearena.delete:
    description: Allows the deletion of arenas
    default: false
  ultimatearena.disable:
    description: Allows the disabling of arenas
    default: false
  ultimatearena.enable:
    description: Allows the enabling of arenas
    default: false
  ultimatearena.forcejoin:
    description: Allows the force joining of arenas
    default: false
  ultimatearena.forcestop:
    description: Allows the force stopping of arenas
    default: false
  ultimatearena.kick:
    description: Allows the kicking of players from arenas
    default: false
  ultimatearena.pause:
    description: Allows the pausing of arena start timers
    default: false
  ultimatearena.reload:
    description: Allows the reloading of the UltimateArena plugin
    default: false
  ultimatearena.setdone:
    description: Allows the usage of /ua done
    default: false
  ultimatearena.setpoint:
    description: Allows the usage of /ua setpoint
    default: false
  ultimatearena.start:
    description: Allows the force starting of arenas
    default: false
  ultimatearena.stop:
    description: Allows the usage of /ua stop
    default: false
  ultimatearena.build:
    description: Allows the breaking and placing of blocks in arenas
    default: false
  ultimatearena.join:
    description: Allows the player to join arenas
    default: true